name: helmet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.3
  get: 4.1.4
  flutter: 
    sdk: flutter
  flutter_svg: ^0.22.0
  lint: ^1.5.3
  flutter_icons: ^1.1.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
   - assets/
   - assets/locales/

  fonts:
   - family: SourceSans
     fonts:
      - asset: fonts/SourceSansPro-Black.ttf
      - asset: fonts/SourceSansPro-Bold.ttf
      - asset: fonts/SourceSansPro-Italic.ttf
        style: italic
      - asset: fonts/SourceSansPro-Light.ttf
      - asset: fonts/SourceSansPro-Regular.ttf

